package views;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import controllers.HouseholdController;
import exception.HouseholdAlreadyExistsException;
import exception.HouseholdNotExist;
import exception.InvalidHouseholdDataException;
import exception.MemberNotFoundException;
import exception.ServiceException;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.stage.Modality;
import javafx.stage.Stage;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.control.ToggleButton;
import models.Household;
import models.Member;
import services.HouseholdService;
import services.HouseholdServiceImpl;
import services.MemberService;
import services.MemberServiceImpl;
import utils.SceneUtils.HouseholdDialogHandler;

public class ViewHouseholdDialogHandler implements HouseholdDialogHandler {

	
	// You need to initialize this
	private HouseholdController householdController; // You need to initialize this
	private MemberService memberService;
	
	private Household currentHousehold;
	private Runnable onSuccessCallback;
	private boolean isEditMode = false;


	// Text fields
	@FXML
	private TextField txtId;
	@FXML
	private TextField txtHouseholdNumber;
	@FXML
	private TextField txtOwnerId;
	@FXML
	private TextField txtOwnerName;
	@FXML
	private TextField txtAddress;
	@FXML
	private TextField txtArea;
	@FXML
	private TextField txtPhone;
	@FXML
	private TextField txtEmail;
	@FXML
	private TextField txtHouseholdSize;
	@FXML
	private TextField txtCreationDate;

	// Controls
	@FXML
	private ToggleButton toggleEditMode;
	@FXML
	private Button btnUpdate;
	@FXML
	private Button btnClose;
	@FXML
	private Button btnMemberDetails;
	@FXML
	private Label lblRequiredNote;

	
	public MemberService getMemberService() {
		return memberService;
	}

	public void setMemberService(MemberService memberService) {
		this.memberService = memberService;
	}

	public HouseholdController getHouseholdController() {
		return householdController;
	}

	public void setHouseholdController(HouseholdController householdController) {
		this.householdController = householdController;
	}

	// Fields that should never be editable (auto-generated by system)
	private static final String VIEW_MODE_STYLE = "-fx-background-color: #f5f5f5; -fx-border-color: #d0d0d0; -fx-border-radius: 5; -fx-background-radius: 5;";
	private static final String EDIT_MODE_STYLE = "-fx-background-color: white; -fx-border-color: #43A5DC; -fx-border-radius: 5; -fx-background-radius: 5;";


	@Override
	public void setOnSuccessCallback(Runnable callback) {
		this.onSuccessCallback = callback;
	}
	
	public void updateAfterMemberDialog() throws ServiceException, HouseholdNotExist {
		currentHousehold = householdController.getHouseholdDetails(currentHousehold.getId());
		System.out.println("do heree");
		System.out.println(currentHousehold.toString());
		this.txtOwnerId.setText( currentHousehold.getOwnerId() );;
		this.txtOwnerName.setText(currentHousehold.getOwnerName()); ;
		this.txtHouseholdSize.setText(currentHousehold.getHouseholdSize()+"");
	}

	// TODO: sua thanh controller chu ko phai la service nhi ?

	@Override
	public void setHousehold(Household household) {
		this.currentHousehold = household;
		fillFormData();
		setViewMode(); // Start in view mode
	}

	private void fillFormData() {
		if (currentHousehold != null) {
			txtId.setText(String.valueOf(currentHousehold.getId()));
			txtHouseholdNumber.setText(currentHousehold.getHouseholdNumber());

			// For owner ID, extract from ownerName field or use separate field if available
			// Assuming you have a way to get owner ID from your Household model
			if (currentHousehold.getOwnerId() != null) {
				txtOwnerId.setText(currentHousehold.getOwnerId());
			}
			txtOwnerName.setText(currentHousehold.getOwnerName());

			txtAddress.setText(currentHousehold.getAddress());
			txtArea.setText(currentHousehold.getArea());
			txtPhone.setText(currentHousehold.getPhone());
			txtEmail.setText(currentHousehold.getEmail());
			txtHouseholdSize.setText(String.valueOf(currentHousehold.getHouseholdSize()));
			txtCreationDate.setText(currentHousehold.getCreationDate().toString());
		}
	}

	@FXML
	private void handleToggleEditMode() {
		isEditMode = toggleEditMode.isSelected();

		if (isEditMode) {
			setEditMode();
		} else {
			setViewMode();
		}
	}

	private void setViewMode() {
		isEditMode = false;
		toggleEditMode.setSelected(false);
		toggleEditMode.setText("Tắt");
		toggleEditMode.setStyle(
				"-fx-background-color: #ffffff; -fx-text-fill: #43A5DC; -fx-cursor: hand; -fx-background-radius: 15;");

		// Disable all editable fields
		setFieldEditable(txtHouseholdNumber, false);
		setFieldEditable(txtOwnerId, false);
		setFieldEditable(txtOwnerName, false);
		setFieldEditable(txtAddress, false);
		setFieldEditable(txtArea, false);
		setFieldEditable(txtPhone, false);
		setFieldEditable(txtEmail, false);

		// Update button disabled
		btnUpdate.setDisable(true);
		btnUpdate.setStyle(
				"-fx-background-color: #43A5DC; -fx-text-fill: white; -fx-cursor: hand; -fx-background-radius: 5; -fx-opacity: 0.5;");

		// Hide required fields note
		lblRequiredNote.setVisible(false);
	}

	private void setEditMode() {
		isEditMode = true;
		toggleEditMode.setSelected(true);
		toggleEditMode.setText("Bật");
		toggleEditMode.setStyle(
				"-fx-background-color: #43A5DC; -fx-text-fill: white; -fx-cursor: hand; -fx-background-radius: 15;");

		// Enable editable fields (but not system-generated ones)
		
		
		setFieldEditable(txtAddress, true);
		setFieldEditable(txtArea, true);
		setFieldEditable(txtPhone, true);
		setFieldEditable(txtEmail, true);

		// System-generated fields remain disabled
		setFieldEditable(txtOwnerId, false); 
		setFieldEditable(txtHouseholdNumber, false);
		setFieldEditable(txtOwnerName, false);
		setFieldEditable(txtId, false);
		setFieldEditable(txtHouseholdSize, false);
		setFieldEditable(txtCreationDate, false);

		// Update button enabled
		btnUpdate.setDisable(false);
		btnUpdate.setStyle(
				"-fx-background-color: #43A5DC; -fx-text-fill: white; -fx-cursor: hand; -fx-background-radius: 5; -fx-opacity: 1.0;");

		// Show required fields note
		lblRequiredNote.setVisible(true);
	}

	private void setFieldEditable(TextField field, boolean editable) {
		field.setEditable(editable);
		if (editable) {
			field.setStyle(EDIT_MODE_STYLE);
		} else {
			field.setStyle(VIEW_MODE_STYLE);
		}
	}

	@FXML
	private void handleUpdate() throws HouseholdNotExist, HouseholdAlreadyExistsException, MemberNotFoundException,
			InvalidHouseholdDataException {
		if (!isEditMode) {
			System.out.println("Update attempted while not in edit mode");
			return;
		}

		System.out.println("Update button clicked in edit mode");

		// Validate required fields
		if (!validateRequiredFields()) {
			// Show error message (you can implement your own error handling here)
			System.out.println("Validation failed - required fields are empty");
			return;
		}

		try {

			// Update the household object with new values
			updateHouseholdFromForm();

			// TODO: Add your update logic here (save to database, etc.)
			 householdController.updateHousehold(currentHousehold);

			// After successful update, call the callback
			if (onSuccessCallback != null) {
				onSuccessCallback.run();
			}

			// Switch back to view mode after successful update
			setViewMode();

			showSuccessDialog("Success", "Cập nhật thông tin hộ khẩu thành công!");
			System.out.println("Household updated successfully");

		} catch (Exception e) {
			showErrorDialog("Update Error", "Có lỗi xảy ra khi cập nhật: " + e.getMessage());
			e.printStackTrace();
		}

	}

	private boolean validateRequiredFields() {
		return !txtHouseholdNumber.getText().trim().isEmpty() && !txtOwnerId.getText().trim().isEmpty()
				&& !txtAddress.getText().trim().isEmpty() && !txtArea.getText().trim().isEmpty();
	}


	private void updateHouseholdFromForm() throws ServiceException {
		if (currentHousehold != null) {
			String address = txtAddress.getText().trim();
			String area = txtArea.getText().trim();
			String phone = txtPhone.getText().trim();
			String email = txtEmail.getText().trim();
			
			if (!currentHousehold.getAddress().equalsIgnoreCase(address) ||
					!currentHousehold.getArea().equalsIgnoreCase(area) ||
					!currentHousehold.getPhone().equalsIgnoreCase(phone) ||
					!currentHousehold.getEmail().equalsIgnoreCase(email)) {
				// Update only the editable fields
				currentHousehold.setAddress(address);
				currentHousehold.setArea(area);
				currentHousehold.setPhone(phone);
				currentHousehold.setEmail(email);
				return;
			}
			throw new ServiceException("Please update at least 1 field!");
		}
	}

	@FXML
	private void handleViewMemberDetails() throws HouseholdNotExist {
		if (currentHousehold == null) {
			showErrorDialog("Error", "Không có thông tin hộ khẩu!");
			return;
		}

		try {
			System.out.println("Getting members for household ID: " + currentHousehold.getId());
			// Get members directly from the controller
			List<Member> members = householdController.getMembers(currentHousehold.getId());

			if (members == null || members.isEmpty()) {
				System.out.println("No members found for household ID: " + currentHousehold.getId());
				showInfoDialog("Thông tin", "Hộ khẩu này chưa có thành viên nào!");
				return;
			}

			System.out.println("Found " + members.size() + " members for household " + currentHousehold.getId());
			for (Member member : members) {
				System.out.println("Member: " + member.getId() + " - " + member.getFullName() + " - " + member.getHouseholdId());
			}

			// Open member details dialog
			openMemberDetailsDialog(currentHousehold, txtHouseholdSize, members, () -> {
				try {
					updateAfterMemberDialog();
				} catch (ServiceException | HouseholdNotExist e) {
					System.err.println("Error updating after member dialog: " + e.getMessage());
					e.printStackTrace();
					showErrorDialog("Error", "Có lỗi xảy ra khi cập nhật thông tin: " + e.getMessage());
				}
			});

		} catch (ServiceException e) {
			System.err.println("Error getting members: " + e.getMessage());
			e.printStackTrace();
			showErrorDialog("Error", "Có lỗi xảy ra khi lấy thông tin thành viên: " + e.getMessage());
		}
	}

	private void openMemberDetailsDialog( Household household, TextField txtHouseholdSize, List<Member> members, Runnable onSuccess) {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/views/MemberDetailsDialog.fxml"));
			Parent root = loader.load();
//			System.out.println("openMemberDetailsDialog  1");
			
			MemberDetailsDialogHandler controller = loader.getController();
//			System.out.println("openMemberDetailsDialog  1");
			controller.setMembers(members);
			controller.setHouseholdController(householdController);
			controller.setHousehold(household);
			controller.setTxtHouseholdSize(txtHouseholdSize);
			controller.setHouseholdInfo(currentHousehold.getHouseholdNumber(), currentHousehold.getOwnerName());
			controller.setOnSuccessCallback(onSuccess);
//			System.out.println("openMemberDetailsDialog  1");
			Stage stage = new Stage();
			stage.setTitle("Chi tiết thành viên hộ khẩu");
			stage.setScene(new Scene(root));
			stage.initModality(Modality.APPLICATION_MODAL);
			stage.initOwner(btnMemberDetails.getScene().getWindow());
//			System.out.println("openMemberDetailsDialog  1");
			stage.show();

		} catch (IOException e) {
			showErrorDialog("Error", "Không thể mở cửa sổ chi tiết thành viên!");
			e.printStackTrace();
		}
	}

	@FXML
	private void handleClose() {
		// After successful update, call the callback
		if (onSuccessCallback != null) {
			onSuccessCallback.run();
		}
					
		System.out.println("Closing view household dialog");
		((Stage) btnClose.getScene().getWindow()).close();
	}

	// Utility methods for dialogs
	private void showErrorDialog(String title, String message) {
		Alert alert = new Alert(Alert.AlertType.ERROR);
		alert.setTitle(title);
		alert.setHeaderText(null);
		alert.setContentText(message);
		alert.showAndWait();
	}

	private void showSuccessDialog(String title, String message) {
		Alert alert = new Alert(Alert.AlertType.INFORMATION);
		alert.setTitle(title);
		alert.setHeaderText(null);
		alert.setContentText(message);
		alert.showAndWait();
	}

	private void showInfoDialog(String title, String message) {
		Alert alert = new Alert(Alert.AlertType.INFORMATION);
		alert.setTitle(title);
		alert.setHeaderText(null);
		alert.setContentText(message);
		alert.showAndWait();
	}

	// Utility methods for external access
	public boolean isInEditMode() {
		return isEditMode;
	}

	public void forceViewMode() {
		setViewMode();
	}

	public void forceEditMode() {
		setEditMode();
	}
}